# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170617_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 20, 25, 44, 117990)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 20, 25, 44, 117028)),
        ),
    ]
