# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170709_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 22, 1, 50, 805384)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 22, 1, 50, 804434)),
        ),
    ]
