# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('college', models.CharField(max_length=1000)),
                ('school', models.CharField(max_length=1000)),
                ('jobs', models.CharField(max_length=5000)),
                ('internships', models.CharField(max_length=5000)),
                ('projects', models.CharField(max_length=5000)),
                ('skills', models.CharField(max_length=1000)),
                ('training', models.CharField(max_length=5000)),
                ('research', models.CharField(max_length=3000)),
                ('additional', models.CharField(max_length=3000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
