# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='freelancers_pics'),
        ),
    ]
