# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancerprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs1', models.CharField(max_length=5000)),
            ],
        ),
    ]
