# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='jobs1',
            new_name='jobs',
        ),
    ]
